### ISSUE TITLE
integration to arxiv2notion

### ISSUE THREAD

**Issue by denkiwakame** [wangjksjtu/arxiv2notionplus#1]
@wangjksjtu 

Hi, I'm an original author of https://github.com/denkiwakame/arxiv2notion and happened to know this repository today.
I'm really impressed that this repository has done the major todos of the original repository, solid work. Thank you!

- [x] create notion database template for easier installation
- [x] multi-select authors
- [x] enhancement in documentation
- [x] support & examples for other browsers

I have been busy for working on some other research projects and, it's embarrassing, have left these todos for a loooong time on this extension (as in https://github.com/denkiwakame/arxiv2notion/issues/3).

I would like to ask you if you're interested in merging these enhancements to the original repository (as pull requests).
After releasing the arxiv2notion, which was originally my personal toolkit, I found that there exists more potential users and demands for this extension than I expected. 
While we can also plan to release this extension on Chrome Store, the users may be a bit confused if they find multiple versions (e.g. arxiv2notion / arxiv2notion+ / arxiv2notion++...).

It would be appreciated if I could welcome you as a core maintainer of arxiv2notion (will add acknowledgment for you on README). No worries that I still can review and commit codes when I have some time.
I'm also considering to move the namespace of arxiv2notion to a group like this (https://github.com/neoclide) in the future.

Could you provide your opinion on this ?

**Comment by wangjksjtu** [comment]
Hi @denkiwakame, Thanks for reaching out and the awesome arxiv2notion project!! I created this repo just for convenience and my personal use case as I imagine it might take a longer time to iterate over the PR/review procedure and more communication costs. Glad to know that you are aware of this work and also active in communication!

I totally agree with the plan to integrate these new features arxiv2notion and release a unified version for users. Specifically, there are the TODO items for us

- [ ] land new features as PRs to https://github.com/denkiwakame/arxiv2notion 
- [ ] Prepare release on the Chrome store, other stores
- [ ] move the namespace of arxiv2notion to a group

I will allocate some time for the first item after the deadline for neurips (1 month left) ;)  Or feel free to merge/move new features to your original repo (this repo is also under MIT) if you want to do it earlier. Does this plan sound good?

Thanks again for reaching out, I am pleased to become a member/maintainer for this project. In general, I feel this tool is simple yet super helpful for the researchers who are using Notion to organize/track the literature. Nice initial work!!

**Comment by denkiwakame** [comment]
@wangjksjtu 

Thank you so much for your prompt response! have invited you as a collaborator to https://github.com/denkiwakame/arxiv2notion .
Here are my thoughts. I'd appreciate if you can give me your opinion on these points when you have enough time. Good luck with your NeurIPS submission :+1: 

## 1) creating PRs for merging arxiv2notionplus
- a. A simplest way is to create one pull request which merges bb16c4e7500f80c0c7663e2ad85c97c0ff791e5e into  2d0fa07a3e1acb5d8c631e89565ec3c3bea48a55 with a careful review and some minor changes.
- b. Another way is to create feature-wise PRs, which make individual changes clear to other developers.

To me, whichever is OK. Fortunately, (a). will not become such a big change in this case. After merging, I will create a changelog and release the new version by tag. ​

## 2) who to do these PRs
> I will allocate some time for the first item after the deadline for neurips (1 month left) ;) Or feel free to merge/move new features to your original repo (this repo is also under MIT) if you want to do it earlier. Does this plan sound good?

- As my respect for your effort on these commitments, even if I create PRs instead, I will keep the git commit author by your name. (It simply means that I don't overwrite your commitment on the git log).
- If you mind some communication costs during your paper submission, I can create a 1) PR draft instead. 
  - I may request some review (e.g. prompt check for acknowledgment), but you can do it after the neurips deadline.
- I'm not in a hurry (i need to finish some paper reviewer duty and journal submission this month 😢) , but first creating PR ``draft`` by my side sounds good for convenience. 

## 3) release on the Chrome store
- will be discussed in https://github.com/denkiwakame/arxiv2notion/issues/5

## 4) move the namespace of arxiv2notion to a group (side topic)
- What motivated me to develop extension is that we can find few number of utility tools for researchers than those for developers.
- Now I casually imagine that It would be helpful to create such a namespace organization that curates utilities for researchers, 
  - Transferring a repository to such an open-community namespace will encourage other users to commit to the tools and may helps to know other utilities or better techniques.
- However, we should also be aware of some side effects for transferring a repository https://docs.github.com/en/enterprise-cloud@latest/repositories/creating-and-managing-repositories/transferring-a-repository
  - I think we can continue discussion on this after 1)-3).

Thanks again for your commitments and kind communication, you can reply when u have time.

**Comment by denkiwakame** [comment]
Dear @wangjksjtu,

I sincerely apologize for the long time since we last contacted.
Due to personal reasons, I haven't had enough time to maintain the extension. However, I have finally resumed maintaining it.
I wanted to inform you that several features (authors, comments, and date properties) have been merged into arxiv2notion https://github.com/denkiwakame/arxiv2notion/pull/6.
I have also refactored parts of the code you added. Please take a look to review what has changed.

Your contribution is now listed in the original repository: https://github.com/denkiwakame/arxiv2notion/graphs/contributors
Thank you once again for being a user of my extension and for your contribution to reorganize the documentation.

I have also submitted a review request to the Chrome Store.

As long as the original extension is served under the MIT License, you can still distribute arxiv2notion plus. However, you cannot overwrite my copyright for this extension. You can add your own copyright notice in addition to mine. The biggest contribution of arxiv2notionplus is the improvement of documentation; more than 90% of the extension's code is still written by me. I would appreciate it if you could keep my copyright notice `(c) 2022 denkiwakame` in the LICENSE.

```
MIT License

Copyright (c) 2022 denkiwakame

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

**The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.**
```

**Comment by wangjksjtu** [comment]
Thanks so much for the follow-up and great integration!! Also, apologize for not having time for this project. I have changed the license as you suggested. Thanks again for creating this tool for the community ;)
