### ISSUE TITLE
Comment type

### ISSUE THREAD

**Issue by messier202** [wangjksjtu/arxiv2notionplus#2]
https://github.com/wangjksjtu/arxiv2notionplus/blob/a73d3231f27cd8449e2b5a4d4e71da7b792f2969/src/js/notion.js#L120
In README, comment type is Text, while the plugin couldn't work properly if I don't set it to URL type in notion.

**Comment by wangjksjtu** [comment]
Thanks for reporting that!! yeah, comment type is `url`! thanks for recognizing the issue is README!
